[package]
name = "siege-color"
version = "0.3.0-unstable"
authors = ["Mike Dilger <mike@optcomp.nz>"]

[dependencies]
siege-math = { path = "../siege-math" }
float-cmp = { git = "https://github.com/mikedilger/float-cmp" }
