[package]
name = "siege-color"
version = "0.3.0"
authors = ["Mike Dilger <mike@optcomp.nz>"]

[dependencies]
siege-math = { git = "ssh://mike@git.gnomonicgames.com/data/git/siege-math.git", branch="0.3" }
float-cmp = "0.4"
